name: Upload Python Package
on:
  release:
    types: [published]

jobs:
  release-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'   # pin to a concrete version you test against

      - name: Install core + publish dependencies
        run: |
          python -m pip install --upgrade pip uv
          # Install only the runtime deps + the tools we need for building/publishing
          uv sync --group publish

      - name: Unit Tests
        # Install the *dev* extras only for the test step
        run: |
          uv sync --group 
          uv run pytest

      - name: Build package
        run: uv run python -m build   # uses the already‑installed `build`

      - name: Upload dists (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1