name: Run Unit Tests
on:
  push:
    branches: [ dev, feature/* ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv
        uv sync --dev
    - name: Run tests
      run: |
        uv run python -m pytest